#!/usr/bin/env python

import argparse

import irc

#Connection(nick="nickenbot", server="irc.snoonet.org")
connection = irc.Connection()
connection.connect()
connection.recv_message()

parser = argparse.ArgumentParser(description='A simple IRC bot.')
args = parser.parse_args()
